### ISSUE TITLE
Must the scope path be case sensitive upon service worker registration?

### ISSUE THREAD

**Issue by ericj17** [TalAter/UpUp#102]
Hi,

Is it possible to make the scope path check case in-sensitive during service worker registration? Or is there a security reason to do so?

## Expected Behavior
Can Service Worker be registered regardless of the casing of the scope path?

Expecting the ServiceWorker registration to work whether I access the scope is '/XYZ.ABC.Web/' or '/xyz.abc.web/'

## Current Behavior
I get the following error when trying to register the service worker when accessing the URL https://localhost/XYZ.ABC.Web

> The path of the provided scope ('/XYZ.ABC.Web/') is not under the max scope allowed ('/xyz.abc.web/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.
> 
> Failed to load resource: net::ERR_INSECURE_RESPONSE
> 
> ServiceWorker registration failed: SecurityError: Failed to register a ServiceWorker: The path of the provided scope ('/XYZ.ABC.Web/') is not under the max scope allowed ('/xyz.abc.web/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope. 

Registration is fine if I access https://localhost/xyz.abc.web

## Context
We cannot ensure the user access the web application with an all lower cased URL.

## Your Environment
I've put the upup.sw.js within the root of a ASP.NET MVC project

Thank you,
Eric

**Comment by TalAter** [comment]
> Must the scope path be case sensitive upon service worker registration?

Yes.

That is a security limitation set by the browser.

URLs are case sensitive. Visiting https://www.youtube.com/watch?v=kh29_SERH0Y will get your heart pumping... change the Y at the end to y, and it is a broken url.

Similarly, a path of `/XYZ.ABC.Web/` and `/xyz.abc.web/` are two different things.
