### ISSUE TITLE
Can't resolve with npm

### ISSUE THREAD

**Issue by ericelliott** [TalAter/UpUp#104]
Cannot resolve module 'upup'

```
npm install --save upup
```

```
const UpUp = require('upup'); // error here
```
## Expected Behavior

Should resolve.

## Current Behavior

`package.json` links to non-existent `index.js` in the project root.

## Possible Solution

Looks like this issue is resolved in 0.3.0, but it's unpublished.

**Comment by TalAter** [comment]
Hey @ericelliott 
I have just published 0.3.0 to NPM, hopefully this should resolve this.

Have you been using UpUp? Anything you can share?

**Comment by ericelliott** [comment]
I've known about UpUp for a while, but I've just started trying to use it for a production app for the first time. I figured it would give me a fast-track to just get the service worker working.

So far it seems to be OK.

Can't share yet, sorry. =)

**Comment by TalAter** [comment]
@ericelliott It is OK :)

The goal here was to create a very easy to use solution for one specific use case - a fallback for when your users are offline.

If you're diving deeper into writing your own service workers, I would suggest checking out two other things I have been working on:

* [`cache.adderall()`](https://www.talater.com/adderall/) which speeds up your service worker updates.
* Building Progressive Web Apps - My book which is out on early access now http://shop.oreilly.com/product/0636920052067.do

**Comment by ericelliott** [comment]
You may be interested to know that I have UpUp pointing to my primary index file, not a dedicated offline fallback. It's a simple app, so it's easy (so far) to list all of the network-loaded assets. The experience both online and offline is pretty much identical.
