### ISSUE TITLE
How to remove website bar  ?

### ISSUE THREAD

**Issue by jessicastorm1986** [TalAter/UpUp#105]
When i save https://www.talater.com/upup/  to home screen, why do i see web browser's bar ? PWA's are not supposed to show that, how can i hide it ?  and how can i use manifest to show icon and other stuff ?

**Comment by TalAter** [comment]
Hi @jessicastorm1986 

Controlling the way a progressive web app opens is done using a (https://w3c.github.io/manifest/)[web app manifest] file. You can use that file to set the visibility of the address bar (`"display": "standalone"`), define icons (`"icons"`), and more.

I cover this, and more, in the book [Building Progressive Web Apps](https://pwabook.com/iss).

**Comment by jessicastorm1986** [comment]
Alright thanks, i'll go through this, just 1 question -  what do i do for my IOS users if i am going with progressive web app ? i just cant ignore them and give android users offline experience and ignoring IOS users totally.

**Comment by TalAter** [comment]
I think the best approach is to give each user the best experience her browser can support (aka progressive enhancement). Start with a fully featured app that works across all browsers, then add features on top to improve the experience for users in supported browsers.

**Comment by jessicastorm1986** [comment]
Sorry but i am confused with your answer as-

1. offline experience is not supported in IOS
2. Neither i can send push notifications on IOS mobile :(

But i dont know what all can be done for my IOS users
