### ISSUE TITLE
Cache-Busting Problem

### ISSUE THREAD

**Issue by lucianocn** [TalAter/UpUp#110]
I'm using UpUp with Angular CLI, and it create CSS and JS file names with a HASH, like:
styles.6f851ef5ed61f94dfc02.bundle.css
inline.97f84214598998adf604.bundle.js
scripts.7bf3eef718d3d11d4686.bundle.js
...

So, as I don't know exactly the file names, before the deploy, there's any option to cache all page resources?

Thanks,

**Comment by NekR** [comment]
Use something else like [offline-plugin](https://github.com/NekR/offline-plugin) for webpack if you are using webpack or [sw-precache](https://github.com/GoogleChrome/sw-precache).

Those tools automate everything for you, or you can manually write a build time script which will be taking file names and rewriting them in your code. But that's much harder and more error prone.

**Comment by lucianocn** [comment]
@NekR thanks!
I chose to use the https://github.com/GoogleChrome/sw-precache and it's working perfect!
