### ISSUE TITLE
Javascript does not work in offline mode

### ISSUE THREAD

**Issue by pixeline** [TalAter/UpUp#111]
I'm trying to make this online tool work offline too, as the content does not change often.
https://plancomptablebelge.be

When I test it on an Android 4.4.2 mobile phone, when I put it offline, the [offline.html ](https://plancomptablebelge.be/offline.html) page shows up, but the javascript does not kick in.

Note that it is entirely possible that I didn't do everything right, it's the first time I use upup.js.
So, how I set it up:

File organisation:
```
/upup.js
/upup.sw.min.js
/index.html
/offline.html
/assets/...
```

In index.html
```
<script src="/assets/js/app-min.js?v={VERSION}"></script>
<script src="/upup.js"></script>
<script>
    UpUp.start({
      'content-url': 'offline.html', // show this page to offline users
      'assets': ['/assets/css/app.css', '/assets/js/app-min.js']
    });
</script>
```
in offline.html
`<script src="/assets/js/app-min.js"></script>
`

## Expected Behavior
On mobile in offline mode, the menu icon should reveal the in-page navigation menu.

## Current Behavior
On mobile in offline mode, when clicking on the menu icon, nothing happens.

## Your Environment

* Version used: 0.3.0
* Browser Name and version: chrome on android, latest
* Operating System and version (desktop or mobile): android 4.4.2 (mobile)
* Link to your project: https://plancomptablebelge.be

Thank you!

**Comment by TalAter** [comment]
There seems to be a problem with your upup.sw.min.js file.

It is trying to load https://plancomptablebelge.be/upup.sw.min.js but that file is empty... make sure you have the real file there and that your server serves it right.
