### ISSUE TITLE
Using UpUp with A-Frame

### ISSUE THREAD

**Issue by Jaysonvdw** [TalAter/UpUp#118]
Hi Guys,

Struggling with trying to successfully create an offline PWA incorporating A-Frame.

Followed the tutorial and deployed to Surge (https required for service worker and don't want to only use localhost) but it's not working offline. Here's the Glitch:
https://glitch.com/edit/#!/join/a04ea5ad-49a7-4adc-9cbc-56b47af181c7

Please assist. Thank you.

**Comment by TalAter** [comment]
What do you mean not working? Do you get an error message? It's just not doing anything?

Do you have it live on a website where we can see it not working? Not just the source code?

Thanks 👍

**Comment by Jaysonvdw** [comment]
Hi All,

I actually stumbled across this: [https://davidwalsh.name/dont-wait-serviceworker-adding-offline-support-oneline] which works like a dream. Apologies for any inconvenience.
