### ISSUE TITLE
Add wildcard for assets

### ISSUE THREAD

**Issue by stefanmm** [TalAter/UpUp#123]
## Expected Behavior

Hi,
I think it would be great if we could cache a bunch of content by adding wildcard in assets.
## Possible Solution

For example:
`'assets': ['/','/feed/?paged=*']`
It is boring to add ?paged=1, ?paged=2... and so on. Of course, you'll have to set limit because of possible endless caching. Like: enter value between 0 and 99.

## Your Environment

* Version used: 1.0
* Browser Name and version: Chrome v64.0.3282.140
* Operating System and version (desktop or mobile): Windows 10 PC
* Link to your project: https://www.saznajnovo.com/pwa/

**Comment by TalAter** [comment]
This is impossible to do, as UpUp isn't aware of the content that exists on your website.

You could do this server side by prefilling the `assets` programmatically.
