### ISSUE TITLE
Detect when not hosted on secure server

### ISSUE THREAD

**Issue by TalAter** [TalAter/UpUp#20]
If debug mode and protocol is http and host isn't localhost, show message.

**Comment by mding5692** [comment]
not sure about where you're placing this within the code, but i think this could help:
http://stackoverflow.com/questions/414809/how-do-i-determine-whether-a-page-is-secure-via-javascript  for checking if it is https

**Comment by mding5692** [comment]
and you can also use 
<pre> location.origin </pre> to figure out if its localhost, hope that helps

**Comment by TalAter** [comment]
Thanks.
I plan to use the location object as you suggested to figure it out and display a debug message if there's a problem.

**Comment by TalAter** [comment]
Not needed, already outputs browser's own error message which explains this quite well.
