### ISSUE TITLE
No iPhone support but iPhone picture

### ISSUE THREAD

**Issue by bfred-it** [TalAter/UpUp#35]
Great project! First thing I thought was… iPhone support?! 

scroll click scroll… nope. 

Can you replace the iPhone with a Nexus or something? It seems a bit misleading at the moment, especially considering that ServiceWorkers won't be available on iOS for **at least** one more year: http://caniuse.com/#feat=serviceworkers

**Comment by TalAter** [comment]
Nice catch! Gave me a laugh (especially with your facepalm avatar)

I've spoken with someone on the webkit team, and they are considering ServiceWorkers… so yeah, one more year sounds about right.

I'll look into changing the images/video in the future.

**Comment by bfred-it** [comment]
:+1: 

Facepalming across the internet, every day.
