### ISSUE TITLE
Having trouble getting this to work in Meteor

### ISSUE THREAD

**Issue by hyperh** [TalAter/UpUp#41]
Any tips for getting UpUp to work in a simple Meteor webpage/app? 

I put the `upup.min.js`, `upup.sw.min.js` into `public/` so I can just load them in `<script>`
Usually I get `ReferenceError: Can't find variable: UpUp`

I also tried putting it into a Meteor package, but couldn't get that to work either.

**Comment by AkshatM** [comment]
From the docs,

>Where Should I Place My Files?

>For security reasons, the browser only lets UpUp's ServiceWorker see network requests within its scope.

>The scope that the ServiceWorker can affect is determined by where you placed upup.min.js and upup.sw.min.js. For example, if you place it on https://yoursite.com/js/upup.sw.min.js, UpUp will only be able to show your offline content when users try to look at the /js/ directory.

>This is why it is important to place both files on the same server as your content, and not in a subdirectory. This should idealy be in the root of your site (e.g. https://yoursite.com/upup.min.js).

Are you sure you're putting them in an appropriate folder?

**Comment by KyleKing** [comment]
I don't think UpUp plays well with Meteor, but there is a package that creates the same effect, [appcache](https://atmospherejs.com/meteor/appcache). [To my knowledge, UpUp leverages the [ApplicationCache anyway](http://www.html5rocks.com/en/tutorials/appcache/beginner/) ]
There is a really good guide worth checking out at: https://subvisual.co/blog/posts/45-offline-web-apps-with-meteor that walks through incorporating both groundDB and appcache

**Comment by TalAter** [comment]
Actually AppCache is an older technology, with many drawbacks compared to the new tech used by UpUp... There's even an article on AppCache called Application Cache is a Douchebag  (http://alistapart.com/article/application-cache-is-a-douchebag)

I think @AkshatM is on to something... Did you try placing both JS files in the root folder?

**Comment by KyleKing** [comment]
I had no idea, thanks for clarifying. I guess I fit into the category of someone who only met AppCache in passing...

**Comment by dandv** [comment]
Let's root for [Meteor supporting Service Worker natively](https://github.com/meteor/meteor/issues/5982).
