### ISSUE TITLE
Offline Homepage not working

### ISSUE THREAD

**Issue by DavidMoritz** [TalAter/UpUp#44]
I saw that your homepage (https://www.talater.com/upup/) is running the upup.min.js script and that your settings are all there. However, when I access the site on my iPhone while online, then go into airplane mode and refresh, I don't see any content. Just that little offline dinosaur.

Is there something I am doing wrong?

**Comment by TalAter** [comment]
iPhones still don't support ServiceWorkers which are a requirement for UpUp. I've spoken to someone at Apple, and they said it is something they are looking into.
