### ISSUE TITLE
fetch polyfill

### ISSUE THREAD

**Issue by zwhitchcox** [TalAter/UpUp#50]
Maybe include? https://github.com/github/fetch

Service workers are available before fetch.
```
Service Workers compatibility: Chrome: 40, Firefox: 33
Fetch:                         Chrome: 42, Firefox: 39
```

**Comment by fbender** [comment]
Since this only affects evergreen browsers, adding a polyfill just for them is unnecessary. Plus, the project only claims Fx 41+ compat, so no issue here.
