### ISSUE TITLE
Only serve offline HTML in response to GETs with Accept: text/html

### ISSUE THREAD

**Issue by jeffposnick** [TalAter/UpUp#51]
The [`current fetch handler`](https://github.com/TalAter/UpUp/blob/master/src/upup.sw.js#L24) indiscriminately returns a `Response` with `Content-Type: text/html` whenever the network request fails and there's no entry in the cache.

I would recommend only returning that HTML content as a fallback in response to `fetch` events that specifically want HTML, by checking for a `Accept: text/html` header in the `Request`. You probably also want to only fall back to the default HTML content for HTTP GET requests.

You can see an example of that logic at https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/custom-offline-page/service-worker.js#L30

In your current implementation, a HTTP request for, e.g., an image would result in an invalid HTML response if the network was unavailable and that image wasn't already cached.

See also: https://jakearchibald.com/2014/offline-cookbook/#generic-fallback

**Comment by TalAter** [comment]
@jeffposnick  Nicely caught. I appreciate the deep dive into the code itself. Thank you. :+1: 

I'm not 100% sold on the GET requirement for UpUp, though.

What if a user is filling out a form, and loses connection. We can have the next page say something like "Your data wasn't saved" and below it include a prefilled form which he can simply submit again once he regains connection (I want UpUp to be able to let the page know when the connection is reestablished in a future version).

**Comment by TalAter** [comment]
Thanks again @jeffposnick.

I just used this technique in [PWABook.com](https://PWABook.com) and credited you for it.
