### ISSUE TITLE
Change website to use Android Phone, since ServiceWorkers are not available in iOS

### ISSUE THREAD

**Issue by irae** [TalAter/UpUp#53]
I notice the website for UpUp uses an iPhone screenshot on the layout. This is misleading, since iOS is precisely the browser one can't use ServiceWorkers. I think it would be better to have an Android phone instead.

**Comment by TalAter** [comment]
You're right. I only noticed that after finishing the site, and someone mentioned it.

But since fixing this would require redoing the entire video and graphics from scratch... I prefer to think of that phone as an iPhone looking clone ordered from AliExpress and running Android :)
