### ISSUE TITLE
HTTP POST not working correctly

### ISSUE THREAD

**Issue by matthiasg** [TalAter/UpUp#56]
I have a webapp which uses (on HTTPS in deployment of course) HTTP POST to post a {username:'..',password:''} to an endpoint (api/auth/login).

This works fine usually, but with UpUp the return value i get back is as if an HTTP GET was performed even when the system is online. 

UpUp should not intercept calls to the api at all or interfere at all with any API calls if possible.

Is there something i overlooked ?

**Comment by matthiasg** [comment]
It seems it generally interferes with my authentication methods too. I use https://github.com/sahat/satellizer which add an `Authorization` header to each HTTP api request. Based on the responses i get back it looks like this header element is swallowed somewhere.

**Comment by TalAter** [comment]
Hey @matthiasg 
Sorry for the late reply.
I have just released a new version thanks to a great contribution by @psykzz. Can you please check if this helps solve your issue?

Thank you.
