### ISSUE TITLE
How to clean / terminate / unregister ServiceWorkers

### ISSUE THREAD

**Issue by pixeline** [TalAter/UpUp#57]
I was experimenting with SW but found out it created issues with single sign-on on my project. I removed upup, but the problem stayed. I realized you need to manually unregister SW.

On chrome, you can do that by going to `chrome://serviceworker-internals` and then click on "unregister"

This should go in the Docs somewhere. At least it is here, for now :-)

Thanks!

**Comment by OskarKlintrot** [comment]
Great, that helped me a lot!

**Comment by TalAter** [comment]
Thanks @pixeline.

Could you elaborate a bit on the problem you had on your site so I can try and reproduce the issue?

**Comment by pixeline** [comment]
@TalAter Sure! I'm using an opensource php package : [hybridauth](https://github.com/hybridauth/hybridauth) for a small personal project: http://do-not-forget.me 
When using upup, I could not successfully log in using my Facebook or Gmail account. Upup worked well otherwise. I couldn't find the exact cause so I gave up. I'll give it another spin when I have more time.
