### ISSUE TITLE
Error with PouchDB - Potential CORS Issue?

### ISSUE THREAD

**Issue by chenkie** [TalAter/UpUp#58]
Hello! I'm trying to get PouchDB data sync going while using UpUp, but I'm running into connection errors. I put in [an issue with PouchDB](https://github.com/pouchdb/pouchdb/issues/4513), and they said it might relate to `no-cors` being used by the service worker: https://github.com/TalAter/UpUp/blob/master/src/upup.sw.js#L27.

I've tried removing `no-cors` but it didn't have any effect, so I'm wondering if it might be something else. Any ideas?

Thanks :)

**Comment by vansieleghemstijn** [comment]
Had some issues with this as well, changing the request to mode: "cors" fixed it for me.

https://fetch.spec.whatwg.org/#concept-request-mode

Removing it still results in "no-cors" being used.

**Comment by hnordt** [comment]
`no-cors` is used to make requests to other origins that don't have CORS headers and result in an }__opaque__ response.

With an opaque response you can't get the data returned by request, meaning you can’t check if the request was successful.

That may be the problem. I recommend the UpUp author to change from no-cors to cors.

**Comment by TalAter** [comment]
Sorry for the late response.

I think the latest version released today might help with this issue. I would appreciate it if you could let me know. Thank you.
