### ISSUE TITLE
returning responses offline

### ISSUE THREAD

**Issue by mzimmerman** [TalAter/UpUp#61]
I'm new to ServiceWorkers but in the "offline first" mentality I thought I'd give it a shot. In my use case though, I'd like the ServiceWorker to respond to requests from the application (when offline or not) which requires me to translate the responses that I'd get from the actual webserver.

Is this a use case that upup will support?  It seems to mostly be for static content retrieval.

**Comment by TalAter** [comment]
Hi @mzimmerman,

I'm not sure I understand your question... What do you mean by translating the responses from the webserver?

Can you describe the entire idea in more detail, and hopefully I can help.

**Comment by mzimmerman** [comment]
Here's the online vs offline use case.
Online
1 - App sends json to serviceworker
2 - service worker sends json to webserver
3 - webserver sends to json service worker
4 - service worker sends json to webapp

Offline
1 - App sends json to serviceworker
2 - service worker sends json to webserver (fails)
3 - service worker sends json to webapp stating the response failure (I'd have to generate this specific error with the code in the service worker based off the json sent by the app)

To add more confusion to the mix, I'd like to use a websocket for the communication as it's a near real-time app.

**Comment by TalAter** [comment]
It sounds like you might want to write your own ServiceWorker for this, UpUp specializes in a different use case.
