### ISSUE TITLE
Online/Offline status flag

### ISSUE THREAD

**Issue by ksnyde** [TalAter/UpUp#62]
Is there any chance that the UpUp library could add event for offline/online detection? Would be really nice to be able to query the current status.

**Comment by TalAter** [comment]
This is partially covered by #14 and #42, but there's definitely room to make this an event as you suggest.

Can you describe the use case you have for this, so that we can find the best possible API design for this?

**Comment by ksnyde** [comment]
I'll close both my posts here as I've added my thoughts to https://github.com/TalAter/UpUp/issues/1
