### ISSUE TITLE
ServiceWorker supported flag

### ISSUE THREAD

**Issue by ksnyde** [TalAter/UpUp#63]
It would be great if the UpUp library were able to expose a simple flag that indicates whether the current browser supports ServiceWorkers or not.

**Comment by TalAter** [comment]
This is already open as #1.

It would be helpful if you could describe the use case you have for this, so that we can find the best possible API design for this.

**Comment by ksnyde** [comment]
I've added my thoughts to https://github.com/TalAter/UpUp/issues/1
