### ISSUE TITLE
Write synchronization

### ISSUE THREAD

**Issue by thiagoarrais** [TalAter/UpUp#65]
(Sorry if this isn't the place for that. Feel free to move this discussion anywhere you think is more appropriate.)

I figure you should have enough on you plate with UpUp as it is right now. But have you thought about write synchronization yet? Or do you think of it as out of scope?

The README, tutorial and intro video (I couldn't find any other docs and didn't feel like checking the code _just yet_) all present a read-only use case. What if the user wants to change the checkin date in the hotel reservation? I think the developers could setup a "syncing" script, "upup" that and control the syncing themselves. But do you think UpUp can make things easier there? Do you see UpUp getting into the write/synchronization arena anytime in the near future? Do you want to open that particular can of worms?

**Comment by hnordt** [comment]
You mean offline data syncronization or assets?

If you need offline data sync please use PouchDB, it's awesome. https://pouchdb.com

**Comment by thiagoarrais** [comment]
That _really_ is awesome. Thanks!
