### ISSUE TITLE
All pages on a domain are loaded through UpUp after upup usage

### ISSUE THREAD

**Issue by ovidiugabriel** [TalAter/UpUp#70]
Hi, 

I used a simple test page to test how UpUp is working. I would like to adopt it into a new project.
After I used it, all the requests to my domain are strongly cached and sometimes I can see that offline content on the test page even if the URL in the browser has nothing to do with the UpUp test page.

**Comment by ovidiugabriel** [comment]
How do I unregister/stop the service worker?

**Comment by ovidiugabriel** [comment]
I assume that I have to call [ServiceWorkerRegistration.unregister()](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister)

I tried the following code:

```javascript
pro = navigator.serviceWorker.getRegistrations()
pro.then(function(registrations) {
    for(registration of registrations) {
        registration.unregister()
    }
})
```

but I received _Uncaught (in promise) TypeError: registration.unregister is not a function(…)_
I can see that unregister is not a method on the registration object, so the registration object is not a [ServiceWorkerRegistration](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration)

**Comment by ovidiugabriel** [comment]
However, good tip to manually unregister it from chrome://serviceworker-internals/

**Comment by ovidiugabriel** [comment]
Any method in the UpUp API to unregister a service worker? I can find only start(), addSettings() and debug().

**Comment by hnordt** [comment]
The correct way of doing it is calling registration.unregister():

https://github.com/TalAter/UpUp/blob/master/src/upup.js#L126

The bad news is that UpUp doesn't expose registration.

**Comment by TalAter** [comment]
Duplicate
