### ISSUE TITLE
Having trouble getting this to work on Windows

### ISSUE THREAD

**Issue by mitchrynart** [TalAter/UpUp#87]
I tried the demo of the Offline page on https://www.talater.com/upup/ with a Microsoft Windows machine, but it shows the default offline page in Chrome and Firefox when offline.

Any tips for getting UpUp to work on Windows machines?

**Comment by TalAter** [comment]
It is a bit hard to reproduce what you did based on that description. Did you clone the project and run the test server that came with it on Windows?

Please describe exactly what you did, and reopen the issue so that we can try and help you.
