### ISSUE TITLE
Trouble in Cordova while starting UpUp

### ISSUE THREAD

**Issue by ovidiugabriel** [TalAter/UpUp#89]
Hello, 

I am trying to use UpUp in Cordova and I have checked if service worker is available in Cordova. Test based on TalAter/UpUp#69 

The problem is that the _Service worker is not available in Cordova_.
I found a plugin but this works only for iOS, not for Android: https://github.com/MobileChromeApps/cordova-plugin-service-worker

**Comment by TalAter** [comment]
UpUp depends on service workers being available.

I am closing this issue as it is an external issue with Cordova adding service worker support, and not something we can do anything about.

@ovidiugabriel If you have any luck with that plugin, please share what you find out... I would love to learn from your experience :+1:

**Comment by ovidiugabriel** [comment]
Yes, I understand the nature of this problem (external Cordova issue). Anyway, I stopped using this as the service workers technology is not mature yet. I planned to check if it will be ready for adoption in 1-2 years.
