### ISSUE TITLE
Using Jekyll - serve first 5 articles / posts if site is offline 

### ISSUE THREAD

**Issue by vilav** [TalAter/UpUp#90]
Hello

I'm learning Jekyll and have some experience with HTML/CSS. Is there a method to, when a Jekyll site is offline, make the latest 5 articles available offline (with assets) dynamically?
Any tips would be super helpful. 

Also, if specific files are cached offline, does that mean for future visits those files will no longer make HTTP requests?

Thanks!

**Comment by TalAter** [comment]
You would have to create a page with Jekyll that includes that posts, and cache them with UpUp... The details of the implementation are a Jekyll thing, which I have to admit I am not very familiar with.

Regarding your 2nd question: Those files will still make HTTP connections... UpUp will only serve them if that connection fails.
